Revert "BACKPORT: compiler_attributes.h: Add 'fallthrough' pseudo keyword for switch/case use"
- This reverts commit 55b09c3ec670250d7ba455716e4be53e5d92d139 as for
some reason it causes a build error with GCC 14.0.0.
- The error in question is:
In file included from ./../include/linux/kconfig.h:74,
                 from <command-line>:
../include/linux/compiler_types.h:331:20: error: missing binary operator before token "("
  331 | #if __has_attribute(__fallthrough__)
      |                    ^
In file included from ./../include/linux/kconfig.h:74,
                 from <command-line>:
../include/linux/compiler_types.h:331:20: error: missing binary operator before token "("
  331 | #if __has_attribute(__fallthrough__)
      |                    ^
In file included from ./../include/linux/kconfig.h:74,
                 from <command-line>:
../include/linux/compiler_types.h:331:20: error: missing binary operator before token "("
  331 | #if __has_attribute(__fallthrough__)
      |                    ^

- We can fix fallthrough manually as downstream kernels usually do instead of utilizing this backport.

Change-Id: Ie76c1ea1e727577da6d5a1c34b4313bf77fa165b
Signed-off-by: Cyber Knight <cyberknight755@gmail.com>